variables:
  GIT_BRANCH: "${CI_COMMIT_REF_SLUG}"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - sync

before_script:
  - apk add --no-cache git openssh-client
  - mkdir -p ~/.ssh
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan gitlab.snapp.ir >> ~/.ssh/known_hosts
  - ssh-keyscan github.com >> ~/.ssh/known_hosts

sync_job:
  stage: sync
  script:
    - echo "Starting sync job"
    - git config --global user.email "platform@snapp.cab"
    - git config --global user.name "Platform"
    - git clone git@github.com:snapp-incubator/smapp-sdk-go.git
    - cd smapp-sdk-go
    - git remote add gitlab git@gitlab.snapp.ir:Map/sdk/smapp-sdk-go.git
    - git fetch origin $GIT_BRANCH
    - git fetch gitlab $GIT_BRANCH
    - git checkout gitlab/$GIT_BRANCH
    - git merge gitlab/$GIT_BRANCH
    - git push gitlab $GIT_BRANCH
  only:
    - schedules
