variables:
  GIT_BRANCH: "${CI_COMMIT_REF_SLUG}"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - sync-from-github
  - sync-to-github

sync_from_github_job:
  stage: sync-from-github
  before_script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan gitlab.snapp.ir >> ~/.ssh/known_hosts
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
  script:
    - echo "Starting sync-from-github job"
    - git config --global user.email "platform@snapp.cab"
    - git config --global user.name "Platform"
    - git clone git@github.com:snapp-incubator/smapp-sdk-go.git
    - cd smapp-sdk-go
    - git remote add gitlab git@gitlab.snapp.ir:Map/sdk/smapp-sdk-go.git
    - git fetch origin main
    - git fetch gitlab $GIT_BRANCH
    - git merge gitlab/$GIT_BRANCH
    - git push gitlab HEAD:$GIT_BRANCH
  only:
    - schedules

sync_to_github_job:
  stage: sync-to-github
  before_script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan gitlab.snapp.ir >> ~/.ssh/known_hosts
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
  script:
    - echo "Starting sync-to-github job"
    - git config --global user.email "platform@snapp.cab"
    - git config --global user.name "Platform"
    - git clone git@gitlab.snapp.ir:Map/sdk/smapp-sdk-go.git
    - cd smapp-sdk-go
    - git remote add github git@github.com:snapp-incubator/smapp-sdk-go.git
    - git fetch origin $GIT_BRANCH
    - git fetch github main
    - git merge github/main
    - git push github HEAD:main
  when: manual
