name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.6

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0

  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23
    steps:
      - uses: actions/checkout@v4
      - name: Enable Go modules
        run: echo "GO111MODULE=on" >> $GITHUB_ENV
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: |
          go test -race $(go list ./... | grep -v /vendor/) -v -coverprofile=coverage.out
          grep -v "mock.go" coverage.out > cover.out
      - name: Generate coverage report
        run: go tool cover -func=cover.out